package com.github.throwable.mdc4spring.anno;

import org.springframework.core.annotation.AliasFor;

import java.lang.annotation.*;

/**
 * Defines a parameter that will be added to current MDC. The parameter will be present in all log messages
 * occurred during method invocation.
 * <p>
 * The annotation may be set at method level, at bean level or for any of method arguments.
 * <p>
 * <h3>Annotating method arguments</h3>
 * When <code>{@literal @}MDCParam</code> annotates method argument, a new parameter will be added to current MDC
 * during the method invocation. By default, the parameter will have the argument name and the value the method invoked with.
 * Alternatively you can specify a custom name for the parameter or define an expression that performs a transformation of its original value.
 * <p>
 * <h3>Annotating methods</h3>
 * When annotating a method with <code>{@literal @}MDCParam</code> you can define additional parameters that will be
 * included to MDC during the method invocation. For each parameter you need to specify a unique name and an expression
 * that will be evaluated during every method call.
 * The evaluation context may contain references to:
 * <ul>
 *     <li>Local bean as <code>#root</code> object. You have access to bean's private fields and properties.</li>
 *     <li>All argument values of the invocation referenced by <code>#argumentName</code> variables.</li>
 *     <li>Spring configuration properties available in <code>#environment</code> map.</li>
 *     <li>System properties referenced by <code>#systemProperties</code> variable.</li>
 *     <li>Current class and method names with <code>#className</code> and <code>#methodName</code> variables.</li>
 * </ul>
 * <p>
 * For more information about Spring expressions please refer to <a href="https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#expressions">Spring Expression Language</a> documentation.
 * <p>
 * <h3>Annotating beans</h3>
 * The <code>{@literal @}MDCParam</code> annotation set at bean level has the same effect as if it is applied to each method of the bean.
 * <p>
 * <h3>Limitations</h3>
 * The library uses Spring AOP to intercept annotated method invocations so these considerations must be token into account:
 * <ul>
 *     <li>The method must be invoked from outside the bean scope. Local calls are not intercepted by Spring AOP, thus any method annotation will be ignored in this case.</li>
 *     <li>Spring AOP does not intercept private methods, so if you invoke an inner bean private method, it will have no effect on it.</li>
 *     <li>By default Java compiler does not keep method argument names in generated bytecode, so it may cause
 *     possible problems with parameter name resolutions when using {@literal @}MDCParam. There are three ways to avoid this problem:
 *     <ul>
 *          <li>If you are using Spring Boot and Spring Boot Maven or Gradle plugin all method arguments will already be saved
 *              with their names in generated bytecode, and no additional action is required.</li>
 *          <li>If you are not using Spring Boot plugin you may tell to compiler to preserve method argument names
 *          by adding <code>-parameters</code> argument to javac invocation.</li>
 *          <li>You may also provide parameter names explicitly:
 *          <br><code>public User findUserById({@literal @}MDCParam("userId") String userId)</code></li>
 *     </ul>
 *     </li>
 * </ul>
 * <p>
 * <h3>Sample usage</h3>
 * <blockquote><pre>
 * {@literal @}MDCParam(name = "transaction.id", eval = "#order.transactionId"),
 * {@literal @}MDCParam(name = "client.id", eval = "#order.clientId")
 *  public void createOrder(Order order,
 *                         {@literal @}MDCParam(eval = "name") Queue queue,
 *                         {@literal @}MDCParam Priority priority,
 *                         {@literal @}MDCParam("user.id") String userId)
 * </pre></blockquote>
 * @see WithMDC
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.PARAMETER})
@Repeatable(MDCParams.class)
public @interface MDCParam {
    /**
     * Parameter's name. Optional for method argument annotation, required for method and bean-level annotations.
     */
    @AliasFor("value")
    String name() default "";

    /**
     * Parameter's name. Alias for <code>name</code> attribute.
     */
    @AliasFor("name")
    String value() default "";

    /**
     * Expression to evaluate.
     * For more information please refer to <a href="https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#expressions">Spring Expression Language</a> documentation.
     */
    String eval() default "";
}
